### ISSUE TITLE
Indexing non-English articles

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#270]
The current index is in `en/query-index.xlsx` and I believe we are only adding articles from `/en/publish/*`. For #268, we'd also need the ability to index articles in other languages, e.g. `/jp/publish/*` and add them to a dedicated `jp/query-index.xlsx`.

**Comment by dominique-pfister** [comment]
Not trivial: we currently have a `target` property in `helix-query.yaml` that contains a shared link for the index definition file in OneDrive. We cannot simply add a language variable to that target property (as in replace `en` with `jp`), we need a shared link for *every* language.

**Comment by tripodsan** [comment]
what about either support extending a config?
```yaml
indices:
  raw_index:
    source: html
    fetch: https://{repo}-{owner}.project-helix.page/{path}
    include:
      - en/publish/**/*.(md|docx)
    target: https://adobe.sharepoint.com/:x:/r/sites/TheBlog/Shared%20Documents/theblog/en/query-index.xlsx
    sitemap: en/query-index.json
    properties:
      author:
        select: main > div:nth-of-type(3) > p:nth-of-type(1)
        value: |
          match(el, 'by (.*)')
...
  raw_index_fr:
    extends: raw_index,
    include:
      - fr/publish/**/*.(md|docx)
    target: https://adobe.sharepoint.com/:x:/r/sites/TheBlog/Shared%20Documents/theblog/fr/query-index.xlsx
    sitemap: fr/query-index.json
  raw_index_jp:
    extends: raw_index,
    include:
      - jp/publish/**/*.(md|docx)
    target: https://adobe.sharepoint.com/:x:/r/sites/TheBlog/Shared%20Documents/theblog/jp/query-index.xlsx
    sitemap: jp/query-index.json
....
```    

or simply use yaml aliases:

```yaml
--- 
indices: 
  raw_index: &default
    fetch: "https://{repo}-{owner}.project-helix.page/{path}"
    include: 
      - en/publish/**/*.(md|docx)
    properties: 
      author: 
        select: "main > div:nth-of-type(3) > p:nth-of-type(1)"
        value: "match(el, 'by (.*)')\n"
    sitemap: en/query-index.json
    source: html
    target: "https://adobe.sharepoint.com/:x:/r/sites/TheBlog/Shared%20Documents/theblog/en/query-index.xlsx"
   ....
  raw_index_fr: 
    <<: *default
    include: 
      - fr/publish/**/*.(md|docx)
    sitemap: fr/query-index.json
    target: "https://adobe.sharepoint.com/:x:/r/sites/TheBlog/Shared%20Documents/theblog/fr/query-index.xlsx"
  raw_index_jp: 
    <<: *default
    include: 
      - jp/publish/**/*.(md|docx)
    sitemap: jp/query-index.json
    target: "https://adobe.sharepoint.com/:x:/r/sites/TheBlog/Shared%20Documents/theblog/jp/query-index.xlsx"
```
