### ISSUE TITLE
DOTCOM-25389 - improve focus indicator for cards

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#360]
From https://jira.corp.adobe.com/browse/DOTCOM-25389

*Recommended Changes from Accessibility Team*

```css
 .card:focus-within {
    outline: 1px solid #1473e6;
}
 .card a:focus {
    outline: none;
    text-decoration: underline;
}
```
Also, add `tabindex=“-1”` on image link (anchor tag inside hero div) and teaser link (anchor tag inside teaser paragraph) so that there is only one article link as a tabstop. Currently the same link has 3 tabstops which is redundant. By adding tabindex=“-1”  on image link and teaser link we’re keeping the tabstops to just topic link and actual article link.

**Comment by rofe** [comment]
Alternate suggestion from @yalagand:
```css
.card:focus-within {
  box-shadow: #1473e6 0 0 0 2px;
}
.card:hover {
  box-shadow: #1473e6 0 0 0 2px;
}
.card a:focus {
  text-decoration: underline;
}
.card .content h2 a:after {
  content: '';
  position: absolute;
  top: 0px;
  bottom: 0px;
  left: 0px;
  right: 0px;
}
```
```html
<div class="card">
  <div class="hero">
    <!-- 1. remove link around hero image
         2. remove redundant alt text from hero image -->
    <img class="lazyloaded" src="/hlx_dae8bc5f78f3cdd4a7460f68d77eb3641079029a.jpeg?height=512&amp;crop=3:2&amp;auto=webp" data-src="/hlx_dae8bc5f78f3cdd4a7460f68d77eb3641079029a.jpeg?height=512&amp;crop=3:2&amp;auto=webp" alt="" />
  </div>
  <div class="content">
    <p class="topic"><a href="/en/topics/diversity--inclusion.html" title="Diversity &amp; Inclusion">Diversity &amp; Inclusion</a></p>
    <h2><a href="/en/2020/08/10/bringing-more-diverse-voices-to-the-world.html" title="Bringing more diverse voices to the world">Bringing more diverse voices to the world</a></h2>
    <p class="teaser">
      <!-- 4. remove redundant link around teaser text -->
      Creativity has the power to create change in the world in big and small ways. It has the power to…</p>
    <p class="date">08-10-2020</p>
  </div>
</div>
```
Remove `position: relative` from `.card .content` and add `position: relative` to the `.card` itself.
